---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: echo-a
  pull: if-not-exists
  image: alpine
  commands:
  - echo tenant-a pipeline
  when:
    event:
    - push
